<template>
  <div class="main" ref="elementRef">
    <div class="header">
      <div class="header-wave-animation-container">
        <h1 class="header-wave-animation-container-upfront">Shark Facts</h1>
        <h1 class=header-wave-animation-container-wave>Shark Facts</h1>
      </div>
      <p>Debunking myths and revealing the truth about sharks</p>
    </div>

    <div class="main-content">
      <section class="hero-section">
        <div class="hero-text">
          <h2>Discover the Real Truth About Sharks</h2>
          <p>
            Your chance of being attacked by a shark is 1 in 3.7 million. Learn
            more fascinating facts that will change your perception of these
            magnificent creatures.
          </p>
        </div>
      </section>

      <section class="facts-section">
        <h3>Shark Facts</h3>
        <div class="facts-grid">
          <div class="fact-card">
            <h4>1 in 3.7M</h4>
            <p>Chance of being attacked by a shark.</p>
          </div>
          <div class="fact-card">
            <h4>100M</h4>
            <p>Sharks killed by humans each year.</p>
          </div>
          <div class="fact-card">
            <h4>400+</h4>
            <p>Species of sharks in the ocean.</p>
          </div>
          <div class="fact-card">
            <h4>70%</h4>
            <p>Shark species threatened or endangered.</p>
          </div>
          <div class="fact-card">
            <h4>Ampullae of Lorenzini</h4>
            <p>
              Allow them to detect the electrical fields generated by other
              animals.
            </p>
          </div>
          <div class="fact-card">
            <h4>45 miles per hour</h4>
            <p>Speed of the shortfin mako shark.</p>
          </div>
          <div class="fact-card">
            <h4>Over 400 years old</h4>
            <p>Lifetime of the Greenland shark.</p>
          </div>
          <div class="fact-card">
            <h4>Dermal denticles</h4>
            <p>Tiny tooth-like structures which covered the shark skin.</p>
          </div>
        </div>
      </section>
      <div class="bubbles" ref="bubblesContainer" v-show="!isMobile">
        <Bubble
          v-for="(bubble, index) in bubbles"
          :key="index"
          :size="bubble.size"
          :left="bubble.left"
          :duration="bubble.duration"
          @resetPosition="resetBubblePosition(index)"
        />
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, onBeforeUnmount } from "vue";
import Bubble from "./Bubble.vue";

const bubbles = ref([]);
const isMobile = ref(false);
const elementRef = ref(null);

const createBubble = () => {
  if (bubbles.value.length < 30) {
    const size = Math.random() * 30 + 10;
    const bubble = {
      size: size,
      left: Math.random() * 100,
      duration: Math.random() * 10 + 5,
    };
    bubbles.value.push(bubble);
  }
};

const resetBubblePosition = (index) => {
  bubbles.value[index].left = Math.random() * 100;
  bubbles.value[index].duration = Math.random() * 10 + 5;
};

onMounted(() => {
  for (let i = 0; i < 30; i++) {
    createBubble();
  }
  setInterval(createBubble, 2000);

  if (elementRef.value) {
    const clientWidth = elementRef.value.clientWidth;

    if (clientWidth < 768) {
      isMobile.value = true;
    }
  }
});

onBeforeUnmount(() => {
  clearInterval(createBubble);
  bubbles.value = [];
});
</script>

<style lang="scss">
body {
  font-family: "Arial", sans-serif;
  margin: 0;
  padding: 0;
  color: #ecf0f1;
}

main {
  max-width: 1140px;
  margin: 0 auto;
}

.header {
  text-align: center;
  padding: 50px 20px;
  color: #f1c40f;

  &-wave-animation-container {
    position: relative;

    &-wave {
      color: blue;
      position: absolute;
      top: 0;
      right: 0;
      left: 0;
      animation: waves 4s ease-in-out infinite;
    }
  }

  @keyframes waves {
  0%,
    100% {
		  clip-path: polygon(
			  0% 45%,
			  16% 44%,
			  33% 50%,
			  54% 60%,
			  70% 61%,
			  84% 59%,
			  100% 52%,
			  100% 100%,
			  0% 100%
		  );
	  }

	  50% {
		  clip-path: polygon(
			  0% 60%,
			  15% 65%,
			  34% 66%,
			  51% 62%,
			  67% 50%,
			  84% 45%,
		  	100% 46%,
	  		100% 100%,
  			0% 100%
		  );
	  }
  }

  h1 {
    font-size: 3rem;
    margin: 0;
  }

  p {
    font-size: 1.2rem;
    margin-top: 10px;
  }
}

.main-content {
  padding: 20px;
}

.hero-section {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  margin-bottom: 50px;
}

.hero-text {
  max-width: 700px;

  h2 {
    font-size: 2.5rem;
    margin-bottom: 20px;
  }

  p {
    font-size: 1.2rem;
  }
}

.facts-section {
  text-align: center;
  margin-top: 30px;

  h3 {
    font-size: 2rem;
    margin-bottom: 30px;
  }
}

.facts-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 20px;
}

.fact-card {
  padding: 20px;
  border-radius: 10px;
  transition: transform 0.3s ease, background-color 0.3s ease;

  &:hover {
    transform: translateY(-10px);
    background-color: #38ada9;
  }

  h4 {
    font-size: 2rem;
    margin-bottom: 10px;
  }
}

</style>
